---
- name: Install OpenVPN Server
  remote_user: root
  hosts: all
  vars:
    # EasyRSA
    easyrsa_generate_dh: true
    easyrsa_servers:
      - name: server

    easyrsa_clients:
      - name: client1
        pass: password123456
      - name: client2
        pass: password123456
    easyrsa_pki_dir: /etc/easyrsa/pki

    # OpenVPN
    openvpn_keydir: "{{ easyrsa_pki_dir }}"
    openvpn_clients: "{{ easyrsa_clients | map(attribute='name') | list }}"
    openvpn_download_dir: /tmp/

    openvpn_download_clients: true
    openvpn_open_firewall: true
    openvpn_route_traffic: true
    openvpn_unified_client_profiles: false
    openvpn_management_enable: false
    openvpn_client_to_client_via_ip: true
    openvpn_use_pam: false

    openvpn_server_options:
      - push "redirect-gateway def1"
      - push "dhcp-option DNS 8.8.8.8"
      - push "dhcp-option DNS 208.67.222.222"
      - push "route dhcp-option DNS 208.67.222.222"

    openvpn_route_ranges: []

  roles:
    - role: nkakouros.easyrsa
    - role: Stouts.openvpn
